[package]
name = "ckb-test-chain-utils"
version = "0.39.0-pre"
authors = ["Nervos Core Dev <dev@nervos.org>"]
edition = "2018"
license = "MIT"
description = "TODO(doc): @chuijiaolianying crate description"
homepage = "https://github.com/nervosnetwork/ckb"
repository = "https://github.com/nervosnetwork/ckb"

[dependencies]
ckb-types = {path = "../types", version = "= 0.39.0-pre"}
ckb-db = { path = "../../db", version = "= 0.39.0-pre" }
ckb-store = { path = "../../store", version = "= 0.39.0-pre" }
ckb-chain-spec = { path = "../../spec", version = "= 0.39.0-pre" }
ckb-dao-utils = { path = "../dao/utils", version = "= 0.39.0-pre" }
ckb-traits = { path = "../../traits", version = "= 0.39.0-pre" }
lazy_static = "1.3.0"
faketime = "0.2.0"
ckb-resource = { path = "../../resource", version = "= 0.39.0-pre" }
ckb-db-schema = { path = "../../db-schema", version = "= 0.39.0-pre" }
